<?php


interface Inx_Apiimpl_Recipient_Constants
{

	const UPDATE_EXCEPTION_RECIPIENT_NOT_FOUND = 101;
	
	const UPDATE_EXCEPTION_ILLEGAL_VALUE = 102;

	const UPDATE_EXCEPTION_DUPLICATE_KEY = 103;

	const UPDATE_EXCEPTION_BLACK_LIST = 104;

	
	const BATCH_CHANNEL_CMD_SELECT = 1;

	const BATCH_CHANNEL_CMD_CREATE_AND_SELECT = 2;

	const BATCH_CHANNEL_CMD_CREATE_OR_SELECT = 3;
	
	const BATCH_CHANNEL_CMD_WRITE = 4;

	const BATCH_CHANNEL_CMD_WRITE_IF_NULL = 5;
	
	const BATCH_CHANNEL_CMD_SUBSCRIBE_IF_NULL = 6;
	
	const BATCH_CHANNEL_CMD_UNSUBSCRIBE = 7;

	const BATCH_CHANNEL_CMD_REMOVE = 10;


	const FETCH_FORWARD_DIRECTION = 1;
	
	const FETCH_BACKWARD_DIRECTION = -1;
		
}
